FROM php:8.1-fpm

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip \
    git \
    && docker-php-ext-install pdo pdo_mysql zip bcmath opcache

# Instalar Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Configuración del directorio de trabajo
WORKDIR /app

# Copiar archivos del proyecto
COPY . /app
COPY .env /app/.env

# Ajustar permisos
RUN chmod -R 775 /app/storage /app/bootstrap/cache

# Instalar dependencias de Laravel
RUN composer install --no-dev --optimize-autoloader

# Comandos de Laravel
RUN php artisan migrate --force && php artisan optimize && php artisan storage:link

EXPOSE 8000

# Comando de inicio
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
